version: '3.8'

services:
  ai_model:
    build: ./ai_model
    container_name: autism_ai_model
    networks:
      - autism_network

  backend:
    build: ./backend
    container_name: autism_backend
    ports:
      - "8000:8000"
    networks:
      - autism_network

  frontend:
    build: ./frontend
    container_name: autism_frontend
    ports:
      - "8080:80"
    networks:
      - autism_network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - autism_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - autism_network

networks:
  autism_network: